### ISSUE TITLE
路由缓存问题：不用自行加组件名称，由插件自动注入

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin-docs#13]

**Comment by honghuangdc** [comment]
介绍缓存原理，注意点 
不用自行加组件名称，由插件自动注入

**Comment by Azir-11** [comment]
finish in https://github.com/soybeanjs/soybean-admin-docs/commit/b72e5ab5a15e583fe5be49cf68f3e5944345dd7f
