### ISSUE TITLE
useTable 使用介绍

### ISSUE THREAD

**Issue by honghuangdc** [soybeanjs/soybean-admin-docs#43]

**Comment by Azir-11** [comment]
参考扩展：

关于 useTable 的使用：
项目中 src/hooks/common/table里的useTable 是基于固定结构的接口数据，要想适配成自己的后端结构，请参考以下步骤：
1. 修改类型 Api.Common里面的 PaginatingCommonParams 和 PaginatingQueryRecord
2. 执行 typecheck 命令，根据错误修复

注意：若是接口数据的结构不符合分页结构，请自行在表格的请求函数的里面添加结果的适配，然后在赋值给 useTable 的apiFn
