### ISSUE TITLE
添加核心团队成员及介绍

### ISSUE THREAD

**Issue by Azir-11** [soybeanjs/soybean-admin-docs#63]

**Comment by Azir-11** [comment]
finish in https://github.com/soybeanjs/soybean-admin-docs/commit/e732a71e71638004b41db64f7ea46fd6cd84c852

**Comment by honghuangdc** [comment]
下次可以在提交的commit后面加上 close #issues序号即可自动关闭对应的issues，还有一些关键词 fix fixed close closed等

**Comment by Azir-11** [comment]
> 下次可以在提交的commit后面加上 close #issues序号即可自动关闭对应的issues，还有一些关键词 fix fixed close closed等

okok，提交的时候漏了，后面才想起来有这条issue哈哈哈哈
